"use client";
import { Footer, Header, ProfileSidebar, Sidebar } from "@/components";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter, Mulish } from "next/font/google";
import { useEffect, useState } from "react";

// const inter = Inter({ subsets: ["latin"] });
const mulish = Mulish({
  weight: ["400", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    import("preline");
  }, []);
  return (
    <html lang="en">
      <body className={`${mulish.className} flex justify-between `}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
