// "use client";
import { Footer, Header, ProfileSidebar, Sidebar } from "@/components";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter, Mulish } from "next/font/google";
import { useState } from "react";

// const inter = Inter({ subsets: ["latin"] });
const mulish = Mulish({
  weight: ["400", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const [showSidebar, setshowSidebar] = useState<boolean>(false);
  console.log("App");
  return (
    <html lang="en">
      <body className={`${mulish.className} flex justify-between`}>
        {/* <Header /> */}
        <Sidebar />
        <div className="w-full py-7 mx-10 lg:mx-7 max-w-[1100px]">
          <Header />
          {children}
          {/* <Footer /> */}
        </div>
        <ProfileSidebar />
      </body>
    </html>
  );
}
